INSERT INTO cuisine_types (cuisine_type_id, cuisine_type)
    VALUES (1, 'American'),
           (2, 'Argentinean'),
           (3, 'Armenian'),
           (4, 'Asian'),
           (5, 'Caucasian'),
           (6, 'Chinese'),
           (7, 'European'),
           (8, 'French'),
           (9, 'Georgian'),
           (10, 'German'),
           (11, 'Italian'),
           (12, 'Japanese'),
           (13, 'Mexican'),
           (14, 'Russian'),
           (15, 'Turkish'),
           (16, 'Ukrainian'),
           (17, 'Uzbek'),
           (18, 'Vietnamese');
